### ISSUE TITLE
Trying to deploy Waasabi on an existing Ubuntu cloud VM

### ISSUE THREAD

**Issue by GregSutcliffe** [baytechc/waasabi-init#3]
Hi! I'm the Ansible person mentioned in #2 :)

So I'm trying to deploy Waasabi to evaluate how it can help us with our Matrix-powered conferences - it looks very cool! To that end, I spun up an EC2 machine with Ubuntu 20.04, and set to work.

Having installed latest Node from their repo (Node 16, npx 8) I could install the Waasabi configurator/startup tool. I stepped through this, selecting a local Peertube instance to be installed, and no other extras (I plan to get the basics working and then connect a Matrix account). Here's the resulting config:

```
root@vm# cat .waasabi/instance/waasabi4.ansible.im/setup.json 
{
  "iid": "<redacted>",
  "app": "host",
  "app_dir": "/home/waasabi/host",
  "app_config": "/home/waasabi/host/.env",
  "ui": "live",
  "ui_dir": "/home/waasabi/live",
  "ui_config": "/home/waasabi/live/website.config.js",
  "secret": "<redacted>",
  "strapi_version": "3.6.0",
  "ui_version": "v0.3.0",
  "backend": {
    "type": "peertube"
  },
  "instance": {},
  "services": {
    "postgresql": {
      "enabled": true,
      "host": "127.0.0.1",
      "port": "5432",
      "database": "waasabi",
      "username": "waasabi",
      "password": "<redacted>"
    },
    "peertube": {
      "enabled": "local",
      "local": {
        "version": "v3.2.1",
        "bind": "127.0.0.1",
        "port": "9000",
        "homedir": "/var/www/peertube",
        "systemuser": "peertube"
      },
      "host": "waasabi4.ansible.im",
      "database": "peertube_waasabi",
      "username": "waasabi",
      "password": ""
    }
  },
  "domain": "ansible.im",
  "host": "waasabi4.ansible.im",
  "subdomain": "waasabi4",
  "admin_email": "<redacted>",
  "admin_password": "<redacted>",
  "ssh": {
    "access": "new"
  },
  "title": "Ansible Waasabi 4"
```

(4 because this was my 4th attempt :P)

When I then select a deployment option, Waasabi fails - and that's regardless of which option I choose, I can neither configure the existing host, nor launch a vm. If I launch-vm, I get:

```
✔ What would you like to do? · launch-vm

Local VM instance running on undefined

error: [Error: ENOENT: no such file or directory, open '/root/.npm/_npx/35bdb73ab6def533/node_modules/waasabi/ngrok.yml'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/root/.npm/_npx/35bdb73ab6def533/node_modules/waasabi/ngrok.yml'
}
TypeError: Cannot read properties of undefined (reading 'waasabi')
    at Module.connect (file:///root/.npm/_npx/35bdb73ab6def533/node_modules/waasabi/src/init/ngrok.js:27:38)
    at async startRelay (file:///root/.npm/_npx/35bdb73ab6def533/node_modules/waasabi/src/flow/launch-vm.js:118:3)
    at async Object.launchInVM [as launch-vm] (file:///root/.npm/_npx/35bdb73ab6def533/node_modules/waasabi/src/flow/launch-vm.js:23:3)
    at async default (file:///root/.npm/_npx/35bdb73ab6def533/node_modules/waasabi/src/flow/actions.js:55:7)
    at async file:///root/.npm/_npx/35bdb73ab6def533/node_modules/waasabi/index.js:23:16
```

While if I select "Install on this machine" I just get "Not supported yet".

What's my best path forward? Local instal seems like a possible candidate for using Ansible to manage a local deployment, which I could perhaps contribute to, but first I need to test it :)

**Comment by GregSutcliffe** [comment]
Oh, yes, I also tried "export-config" which gives me a cloud-init - however, I don't have control of the EC2 account, so I can't use it at creation time, and I don't see how to apply it after-the-fact. Is that possible?

**Comment by flaki** [comment]
Oh lordy, yeah I definitely need to clean up the the Ngrok handling (unfortunately without Ngrok there's no way to run anything on a local machine or container so it's a "necessary evil" for now.

To answer your second question, yes, making a guide for waasabi.org on "manual installing" a Waasabi bundle is high on my list of todos actually!

If you want to try, here's a rough rundown:
- you will need root access to the VM/droplet
- you will need to install a couple [packages manually](https://github.com/baytechc/waasabi-config/blob/bc50bbf0867e2e3086890047c4468183a4d7cb2b/src/cloud_init.js#L27), like curl and nginx on a vanilla VM
- you need to create a default [limited `waasabi` user](https://github.com/baytechc/waasabi-config/blob/bc50bbf0867e2e3086890047c4468183a4d7cb2b/src/cloud_init.js#L7) (you can make it sudo although the installer runs as root so it doesn't need this)
- copy the [yaml file](https://github.com/baytechc/waasabi-config/blob/bc50bbf0867e2e3086890047c4468183a4d7cb2b/src/cloud_init.js#L48) to the host, this contains the instructions for setting up the waasabi instance (a glorified bash script, if you will)
- run the [init.sh script](https://github.com/baytechc/waasabi-config/blob/main/src/init_sh.js) in with the correct path to your yaml (as root) to start the installation

The script will print an URL that you should be able to open in a browser to follow the installation process as well :)

My plan is to make this a single shell file or file package with a few guidelines for doing it on an Ubuntu/Debian VM/Container/Docker etc. but have been super busy with RustFest lately :/

**Comment by GregSutcliffe** [comment]
Some notes on trying this:

- The init script needs `setup.INITSCRIPT_VERSION` - I just used `latest`
- First attempt to run it fails with

```
[1/17] metadata: Loading installation metadata…

Status:  http://localhost:53692
[1/17] metadata: Metadata loaded.
[2/17] nginx/main: Configuring Nginx…

[2/17] [##########..........] 50% (1/2)
error: Uncaught (in promise) PermissionDenied: Requires net access to "0.0.0.0:53692", run again with the --allow-net flag
    const listener = Deno.listen({
                          ^
    at Object.opSync (deno:core/01_core.js:142:12)
    at opListen (deno:ext/net/01_net.js:38:17)
    at Object.listen (deno:ext/net/01_net.js:204:17)
    at Server.listenAndServe (https://deno.land/std@0.110.0/http/server.ts:232:27)
    at Module.start (https://waasabi.org/code/init@latest/runtime/logservice.js:39:16)
    at https://waasabi.org/code/init@latest/init.js:41:22
```
- Added that to the deno command. Progress. Got this:
```
[2/17] [##########..........] 50% (1/2)
Output: 
[2/17] [####################] 100% (2/2)
nginx: [emerg] unknown "homedir" variable
Output: 
```
ps shows some dead process:
```
  87047 pts/0    Sl+    0:00  |                   \_ deno run --allow-net --allow-read --allow-write --allow-run https://waasabi.org/code/init@latest/init.js /root/waasabi-init.yml
  87051 pts/0    Z+     0:00  |                       \_ [nginx] <defunct>
  87052 pts/0    S+     0:00  |                       \_ apt-get install certbot python3-certbot-nginx
```
- Seems nginx died. even a kill -9 doesn't clear it
- Killed the apt process instead, which dumped a big stacktrace from deno
- ran apt-get install certbot python3-certbot-nginx myself
- Ran deno again
```
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Error while running nginx -c /etc/nginx/nginx.conf -t.

nginx: [emerg] unknown "homedir" variable
nginx: configuration file /etc/nginx/nginx.conf test failed

The nginx plugin is not working; there may be problems with your existing configuration.
The error was: MisconfigurationError('Error while running nginx -c /etc/nginx/nginx.conf -t.\n\nnginx: [emerg] unknown "homedir" variable\nnginx: configuration file /etc/nginx/nginx.conf test failed\n')
Output: 
[3/17] letsencrypt: HTTPS enabled for waasabi.ansible.im
...
[4/17] [####################] 100% (3/3)
{ uid: "113", gid: "120", home: "/var/lib/postgresql" }
Unstable API 'Deno.run.gid'. The --unstable flag must be provided.
```
- Adding --unstable to the deno run doesn't fix it, must be needed at some lower level

At this point I think I'm probably hitting too many errors to be reliable. What's causing the homedir error? I did not set one explicity when creating the waasabi user but obviously it has one (/home/waasabi)....
```

**Comment by flaki** [comment]
Oh yes, I have a lingering commit somewhere that adds the missing `deno` flags to the deploy, though this many issues with Nginx is very unusual, usually issues emerge around the peertube install, never seen these issues, or particularly the `homedir` one.

As I mentioned before, all feedback is useful, and I have been thinking about ditching nginx for a simpler reverse-proxy solution, this is pushing me even towards doing this, mostly stuck with it as of late because I didn't have the time to re-wire the monstre PeerTube configuration.

Sorry for running into so many issues, there definitely is a lot more work needed until this is sufficiently reliable and configurable :/

**Comment by GregSutcliffe** [comment]
No apology needed. I'm happy to dig into it a bit, but Deno is new to me. Is there a good way to debug / step through the install and figure it out?

**Comment by flaki** [comment]
You will definitely need `--unstable`, you can also just `--allow-all` as this is a sealed throwaway system, you can specify `--verbose` in the commandline to get deno to be a bit more chattier about what's going on that might be worth a try.

**Comment by GregSutcliffe** [comment]
ok using -A -L debug --unstable makes it *very* verbose :)

Looks like it's a config thing? $HOMEDIR is called in the nginx config:
```
root@# grep -ir homedir /etc/nginx/
/etc/nginx/sites-available/default:  root $HOMEDIR/storage;
/etc/nginx/sites-available/default:  #client_body_temp_path $HOMEDIR/storage/nginx/;
/etc/nginx/sites-available/default:    root $HOMEDIR;
/etc/nginx/sites-available/default:    alias $HOMEDIR/peertube-latest/client/dist/$1;
```
which in turn is coming from the waasabi.yml file, I think. Should that be interpolated?

**Comment by flaki** [comment]
My apologies, I didn't quite realize I have _this many_ issues already fixed but unreleased!
You made me look, and it's embarassing that you have been running into the issues that I have fixed already a while back but never had time to cut a release of.

Since RustFest is around the corner I won't be able to do that now, either, but if you want to pick this up next week, [I pushed](https://github.com/baytechc/waasabi-config/tree/wip) all the fixes into an experimental branch over at the Config utility. You'd have to git clone/npm install and run locally but it should pic your config up and with a small amount of luck it would lend you a much better install!

It even has an early [manual install shell script](https://github.com/baytechc/waasabi-config/blob/wip/src/manual_deploy_sh.js) which completely blows my mind because I did _not_ remember creating anything like that until I saw it and reminded me that I used this to set up [live.waasabi.org](https://live.waasabi.org/) as a way to dogfood.

Again, my apologies for having you run in circles while these were sitting tucked away in a folder :see_no_evil:

**Comment by GregSutcliffe** [comment]
Appreciate the help! I'll take a look on Monday and let you know how I get on.
